# instale o rest client no vscode para rodar os requests
# mude de enviroment para testar os requests (ctrl + alt + e) e selecione o enviroment 

### list users
GET {{host}}/api/users?name=Doe

### create user
POST {{host}}/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "email@test1.com.br",
    "password": "123456",
    "role": "ADMIN"
}

### set user uuid
@uuid=c8068e9c-8939-4139-b63d-017d71971bc7

### get one user
GET {{host}}/api/users/{{uuid}}

### update one user
PUT {{host}}/api/users/{{uuid}}
Content-Type: application/json

{
    "name": "Richard Tompson",
    "email": "richard@tompson.com",
    "role": "USER"
}

### filter user
GET {{host}}/api/users?name=richard