### list users
GET http://localhost:3001/api/users

### create new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "email@test4.com.br",
    "password": "123456",
    "role": "ADMIN"
}

### set user uuid
@uuid=065ebc6f-78e8-4383-aeda-f24b4ecc56cf

### get one user
GET http://localhost:3001/api/users/{{uuid}}

### update one user
PUT http://localhost:3001/api/users/{{uuid}}
Content-Type: application/json

{
    "name": "Richard Tompson",
    "email": "richard@tompson.com",
    "role": "USER"
}