### list users
GET http://localhost:3001/api/users?name=Doe

### create user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "email@test1.com.br",
    "password": "123456",
    "role": "ADMIN"
}

### set user uuid
@uuid=3833c394-2e63-4f3b-8aa0-b6c14fd9b8ae

### get one user
GET http://localhost:3001/api/users/{{uuid}}

### update one user
PUT http://localhost:3001/api/users/{{uuid}}
Content-Type: application/json

{
    "name": "Richard Tompson",
    "email": "richard@tompson.com",
    "role": "USER"
}

### filter user
GET http://localhost:3001/api/users?name=richard